/*
  uSTREAM LIGHT-WEIGHT STREAMING ARCHITECTURE
  Copyright (C) 2005 Luis Serrano (luis@kontrol-dj.com) 
  
  Based on DANUBIO STREAMING ARCHITECTURE by Michele Iacobellis (m.iacobellis@nexotech.it)

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

*/

#ifndef CORE_ENUMS_HPP
#define CORE_ENUMS_HPP

namespace uStreamLib {
	/**
	 * These are class identifiers for custom type identification.
	 */
	enum UOSUTIL_Rtti { UOSUTIL_RTTI_OBJECT, UOSUTIL_RTTI_ADDRESS,
	UOSUTIL_RTTI_BASE64, UOSUTIL_RTTI_BUFFER_POOL, UOSUTIL_RTTI_CM_CREATE_PROP,
	UOSUTIL_RTTI_CM_GET_PARAM, UOSUTIL_RTTI_CM_GET_PARAMS, UOSUTIL_RTTI_CM_HELP,
	UOSUTIL_RTTI_CM_SAVE, UOSUTIL_RTTI_CM_SET_PARAM, UOSUTIL_RTTI_CALLBACK,
	UOSUTIL_RTTI_COMMAND, UOSUTIL_RTTI_COMPARATOR, UOSUTIL_RTTI_CONFIG_CALLBACK,
	UOSUTIL_RTTI_CONFIG_MACHINE, UOSUTIL_RTTI_CONFIG_STORAGE,
	UOSUTIL_RTTI_CONFIG_TABLE, UOSUTIL_RTTI_DSO, UOSUTIL_RTTI_DATABUF,
	UOSUTIL_RTTI_ENUMERATION, UOSUTIL_RTTI_FILE, UOSUTIL_RTTI_FILE_COPY_THREAD,
	UOSUTIL_RTTI_FILE_FILTER, UOSUTIL_RTTI_FILE_INPUT_STREAM,
	UOSUTIL_RTTI_FILE_OUTPUT_STREAM, UOSUTIL_RTTI_HASH, UOSUTIL_RTTI_IO_DEVICE,
	UOSUTIL_RTTI_IO_MONITOR, UOSUTIL_RTTI_IO_STATUS_LISTENER,
	UOSUTIL_RTTI_INET_ADDRESS, UOSUTIL_RTTI_INET_SOCK, UOSUTIL_RTTI_INPUT_STREAM,
	UOSUTIL_RTTI_INTERP, UOSUTIL_RTTI_LOGGER, UOSUTIL_RTTI_LOGGABLE, UOSUTIL_RTTI_MD5,
	UOSUTIL_RTTI_MUTEX, UOSUTIL_RTTI_OUTPUT_STREAM, UOSUTIL_RTTI_PSTACK,
	UOSUTIL_RTTI_PVECTOR, UOSUTIL_RTTI_PARAMS, UOSUTIL_RTTI_PRIORITY_QUEUE,
	UOSUTIL_RTTI_PROPERTY, UOSUTIL_RTTI_PROPERTY_GROUP, UOSUTIL_RTTI_QUEUE,
	UOSUTIL_RTTI_SEMAPHORE, UOSUTIL_RTTI_SHARED_DOUBLE, UOSUTIL_RTTI_SHARED_HASH,
	UOSUTIL_RTTI_SHARED_INT, UOSUTIL_RTTI_SHARED_QUEUE, UOSUTIL_RTTI_SHARED_STRING,
	UOSUTIL_RTTI_SHARED_TIMER, UOSUTIL_RTTI_SHARED_UINT, UOSUTIL_RTTI_SIMPLE_QUEUE,
	UOSUTIL_RTTI_SOCK, UOSUTIL_RTTI_STREAM, UOSUTIL_RTTI_SYSTEM,
	UOSUTIL_RTTI_TCP_SERVER_SOCK, UOSUTIL_RTTI_TCP_SOCK, UOSUTIL_RTTI_THREAD,
	UOSUTIL_RTTI_TIMER, UOSUTIL_RTTI_UDP_SOCK, UOSUTIL_RTTI_URL, UOSUTIL_RTTI_USER,
	UOSUTIL_RTTI_UTILS, UOSUTIL_RTTI_VECTOR, UOSUTIL_RTTI_MUTEX_LOCKER,
	UOSUTIL_RTTI_NAMED_PIPE, UOSUTIL_RTTI_MEMORY_INPUT_STREAM,
	UOSUTIL_RTTI_MEMORY_OUTPUT_STREAM, UOSUTIL_RTTI_PVECTOR_UNSAFE,
	UOSUTIL_RTTI_MEMORY_MAPPED_FILE, UOSUTIL_RTTI_MEMORY_MAPPED_VIEW,
	UOSUTIL_RTTI_SCRIPTABLE_COMPONENT, UOSUTIL_RTTI_MACHINE_TASK,
	UOSUTIL_RTTI_MACHINE_TASK_SCHEDULER, UOSUTIL_RTTI_REPORT_ENGINE,
	UOSUTIL_RTTI_REPORTABLE, UOSUTIL_RTTI_LAST_ID };

	/**
	 * These are error codes.
	 */
	enum UOSUTIL_Error { UOSUTIL_ERROR_NO_ERROR = 0,
	UOSUTIL_ERROR_ALLOC_ZERO_SIZE = 1, UOSUTIL_ERROR_OUT_OF_MEMORY = 2,
	UOSUTIL_ERROR_NULL_CONFIG_TABLE = 3, UOSUTIL_ERROR_NULL_CONTEXT = 4,
	UOSUTIL_ERROR_CANNOT_CREATE_DIR = 5, UOSUTIL_ERROR_SOCKET = 6,
	UOSUTIL_ERROR_NULL_CONFIG_MACHINE = 7, UOSUTIL_ERROR_INVALID_TABLE = 8,
	UOSUTIL_ERROR_PROTOCOL = 9, UOSUTIL_ERROR_ITM = 10, UOSUTIL_ERROR_OTM = 11,
	UOSUTIL_ERROR_RESOLVE_ERROR = 12, UOSUTIL_ERROR_DSO = 13,
	UOSUTIL_ERROR_THREAD = 14, UOSUTIL_ERROR_FILE_OPEN = 15,
	UOSUTIL_ERROR_SEMAPHORE = 16 };
}

#endif
